 pipeline {
    agent any

    environment {
        ECR_REGISTRY = "https://398443246513.dkr.ecr.us-east-1.amazonaws.com"
        ECR_REPOSITORY = "ci-ecr"
        DOCKER_IMAGE_TAG = "feature"
    }


  
    stages {

        stage('Clone repository') { 
            steps { 
                script{
                checkout scm
                }
            }
        }
        stage ('Build') {
            steps {
                sh 'pwd'
                sh 'cd account-service'
                sh 'ls -la'
                sh 'mvn clean package'
            }
        }

        
        stage('Build Docker image') {
            steps {
                sh 'docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_IMAGE_TAG .'
      }
    }

        stage('Login to ECR') {
            steps {
                withCredentials([awsEcr(credentialsId: 'aws-credential', region: 'us-east-1')]) {
                    sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY'
        }
      }
    }

        stage('Push Docker image to ECR') {
            steps {
                sh 'docker push $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_IMAGE_TAG'
      }
    }
    }
}
