 pipeline {
    agent any
    tools {
        maven 'maven-3.6.3' 
    }
  
    stages {
        stage ('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    docker build -t ci-ecr .
                    docker tag ci-ecr:latest public.ecr.aws/y0j0v8z3/ci-ecr:latest

                    stage('Deploy') {
            steps {
                script{
                        docker.withRegistry('https://398443246513.dkr.ecr.us-east-1.amazonaws.com', 'ecr:us-east-1:aws-credentials') {
                    app.push("${env.BUILD_NUMBER}")
                    app.push("latest")
                    }
                }
            }
                }
            }
        }
		}
	}
}
